# Create folder 
- name: Create project temporal folder /tmp/back-{{ hostname }}
  file:
    path: /tmp/back-{{ hostname }}
    state: directory

- name: Copy project 
  synchronize:
    src: ./project/
    dest: "/tmp/back-{{ hostname }}"
    
- name: npm install
  npm: 
    path: "/tmp/back-{{ hostname }}/"

# - name: Create project opt folder /opt/pm2Apis/back-{{ hostname }}
#   file:
#     path: /opt/pm2Apis/{{ hostname }}
#     state: directory
#   sudo: yes

- name: Copy project to /var/www
  command: cp -R /tmp/back-{{ hostname }}/ /opt/pm2Apis/{{ hostname }}
  sudo: yes

- name: Create pm2 service API-{{ hostname }}
  command: pm2 start /opt/pm2Apis/{{ hostname }}/app/server.js --name "API-{{ hostname }}"

- name: pm2 startup
  command: pm2 startup
  sudo: yes
