# Create project folders
- name: Create backend project folder /opt/pm2APIs
  file:
    path: /opt/pm2APIs
    state: directory
  become: true

- name: Create backend project folder /opt/pm2APIs/{{ hostname }}
  file:
    path: /opt/pm2APIs/{{ hostname }}
    state: directory
    owner: centos
    group: centos
  become: true

# Create virtualhost
- name: Install VirtualHost file 
  template:
    src: templates/VirtualHost.j2
    dest: /etc/httpd/sites-available/APISSL_{{ hostname }}.conf
  become: true

# Enable site
- name: Enable VirtualHost
  file:
    src: /etc/httpd/sites-available/APISSL_{{ hostname }}.conf
    dest: /etc/httpd/sites-enabled/APISSL_{{ hostname }}.conf
    state: link
  become: true

# Reload httpd
- name: Enable reload httpd on systemctl
  systemd:
    name: httpd
    state: restarted
    enabled: yes
  become: true

# TODO: Move certbot ssl file to sites-available and make link
  
# Create SSL Certbot
#- name: run certbot
#  command: certbot --email devops@talentosoftware.com  --apache -n  -d {{ hostname }}  --agree-tos 
#  sudo: yes