# Create folder 
- name: Create project temporal folder /tmp/back-{{ hostname }}
  file:
    path: /tmp/back-{{ hostname }}
    state: directory

- name: Upload project local --> server
  synchronize:
    src: ./project/
    dest: "/tmp/back-{{ hostname }}"
    
- name: npm install
  npm: 
    path: "/tmp/back-{{ hostname }}/"

- name: Copy project to /var/www
  command: cp -R /tmp/back-{{ hostname }}/. /opt/pm2APIs/{{ hostname }}
#  become: true

- name: Create pm2 service API-{{ hostname }}
  command: pm2 start /opt/pm2APIs/{{ hostname }}/app/server.js --name "API-{{ hostname }}"
  args:
    chdir: /opt/pm2APIs/{{ hostname }}/

- name: pm2 startup
  command: pm2 startup
  become: true

