# Playbook to prepare CentOS 7 to use SwapFile to prevent low memory

- name: Create swapfile
  command: dd if=/dev/zero of=/swapfile bs=1M count=2048 
  become: true

- name: Format swapfile
  command: mkswap /swapfile
  become: true

- name: Change swapfile permissions
  file: path=/swapfile
  become: true

- name: Enable swap
  command: swapon /swapfile
  become: true

- name: Add to fstab
  action: lineinfile dest=/etc/fstab regexp="swapfile" line="/swapfile none swap sw 0 0" state=present
  become: true
