# Playbook to prepare CentOS 7 to use Sites-Available and Sites-Enabled folder

- name: Create folder /etc/httpd/sites-available 
  file:
    path: /etc/httpd/sites-available
    state: directory
  sudo: yes

- name: Create folder /etc/httpd/sites-enabled 
  file:
    path: /etc/httpd/sites-enabled
    state: directory
  sudo: yes

- name: Create httpd config to use sites-enabled config files
  copy:
    content: "IncludeOptional sites-enabled/*.conf"
    dest: "/etc/httpd/conf.d/VirtualHost.conf"
  sudo: yes

- name: Enable reload httpd on systemctl
  systemd:
    name: httpd
    state: restarted
    enabled: yes
  sudo: yes
